# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes
sun:

# Modbus HAS integration
modbushas:
  light: !include include/light.yaml
  binary_sensor: !include include/binary_sensor.yaml

logger:
  default: warning
  logs:
    custom_components.modbushas: debug
    homeassistant.components.modbus: debug
    pymodbus: debug

modbus:
  - name: fatek
    type: tcp
    host: 192.168.100.3
    port: 502
    binary_sensors:
      - name: fatek_dummy_coil_72
        address: 72
        slave: 1
        input_type: coil
        scan_interval: 60

# binary_sensor: !include include/binary_sensor.yaml  # Przeniesione do modbushas

scene: !include scenes.yaml
notify: !include include/notify.yaml
script: !include scripts.yaml

automation: !include automations.yaml
automation old: !include_dir_merge_list include/automation 
