- platform: modbushas
  hub: fatek
  scan_interval: 5
  command_register: 475
  covers:
    - name: gabinet_roleta_1
      register: 1274
      slave: 1
      unique_id: gabinet_roleta_1
    - name: gabinet_roleta_2
      register: 1281
      slave: 1
      unique_id: gabinet_roleta_2
